### Get all notes
GET http://localhost:5000/notes
Accept: application/json

### Create a new note
POST http://localhost:5000/notes
Content-Type: application/json

{
    "title": "coba coba1",
    "content": "cobacobacobacobacobacobacobacobacoba"
}

### Update a note
PATCH http://localhost:5000/notes/16
Content-Type: application/json

{
    "title": "coba coba1",
    "content": "cobacobacobacobacobacobacobacobacoba"
}

### Delete a note
DELETE http://localhost:5000/notes/16

### REGISTER
POST http://localhost:5000/notes/register
Content-Type: application/json

{
    "email": "nazhif@gmail.com",
    "username": "nazhif",
    "password": "passwordku"
}

###

### LOGIN
# ↳ menyimpan cookie accessToken secara otomatis jika server mengatur httpOnly
POST http://localhost:5000/notes/login
Content-Type: application/json

{
    "username": "nazhif",
    "password": "passwordku"
}


### Get all notes
GET http://localhost:5000/token